#Lab3: Create a pie chart to illustrate the distribution of a company's revenue
#across its various business segments. You have collected data on the revenue
#generated by each segment, such as Product A, Product B, Services, and
#Licensing. Share your conclusion/analysis.
#Input:
#segments = ['Product A', 'Product B', 'Services', 'Licensing']
#revenue_percentages = [45, 25, 15, 15]

import matplotlib.pyplot as plt

# Input data
segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]

# Create pie chart
plt.pie(revenue_percentages, labels=segments, autopct='%1.1f%%', startangle=140)
plt.title('Company Revenue Distribution by Business Segment')
plt.show()
